import { PrismaClient, EmploymentType, JobStatus, JobPriority } from '@prisma/client';

const prisma = new PrismaClient();

// ── Clients ───────────────────────────────────────────────────────────────────

const CLIENTS = [
  {
    companyName: 'Infosys BPM Ltd',
    contactPerson: 'Rajesh Nair',
    email: 'rajesh.nair@infosysbpm.com',
    phone: '9820011234',
    city: 'Pune', state: 'Maharashtra', country: 'India', pincode: '411057',
    industry: 'Information Technology',
    website: 'https://www.infosysbpm.com',
    address: 'Plot No. 1, Hinjawadi Phase 2, Rajiv Gandhi Infotech Park',
  },
  {
    companyName: 'Mahindra & Mahindra Ltd',
    contactPerson: 'Suresh Patil',
    email: 'suresh.patil@mahindra.com',
    phone: '9821022345',
    city: 'Mumbai', state: 'Maharashtra', country: 'India', pincode: '400018',
    industry: 'Automobile & Manufacturing',
    website: 'https://www.mahindra.com',
    address: 'Gateway Building, Apollo Bunder',
  },
  {
    companyName: 'Sun Pharmaceutical Industries',
    contactPerson: 'Priya Desai',
    email: 'priya.desai@sunpharma.com',
    phone: '9833033456',
    city: 'Mumbai', state: 'Maharashtra', country: 'India', pincode: '400093',
    industry: 'Pharmaceuticals',
    website: 'https://www.sunpharma.com',
    address: 'Sun House, CTS No. 201B/1, Western Express Highway, Goregaon East',
  },
  {
    companyName: 'HDFC Bank Limited',
    contactPerson: 'Anita Sharma',
    email: 'anita.sharma@hdfcbank.com',
    phone: '9844044567',
    city: 'Mumbai', state: 'Maharashtra', country: 'India', pincode: '400013',
    industry: 'Banking & Financial Services',
    website: 'https://www.hdfcbank.com',
    address: 'HDFC Bank House, Senapati Bapat Marg, Lower Parel',
  },
  {
    companyName: 'Reliance Retail Ventures Ltd',
    contactPerson: 'Vikram Mehta',
    email: 'vikram.mehta@relianceretail.com',
    phone: '9855055678',
    city: 'Mumbai', state: 'Maharashtra', country: 'India', pincode: '400079',
    industry: 'Retail & FMCG',
    website: 'https://www.relianceretail.com',
    address: '3rd Floor, Court House, Lokmanya Tilak Marg, Dhobi Talao',
  },
  {
    companyName: 'Wipro Technologies',
    contactPerson: 'Kiran Kumar',
    email: 'kiran.kumar@wipro.com',
    phone: '9866066789',
    city: 'Bengaluru', state: 'Karnataka', country: 'India', pincode: '560035',
    industry: 'Information Technology',
    website: 'https://www.wipro.com',
    address: 'Doddakannelli, Sarjapur Road, Outer Ring Road',
  },
  {
    companyName: 'Airtel Business',
    contactPerson: 'Neha Singh',
    email: 'neha.singh@airtel.com',
    phone: '9877077890',
    city: 'Gurugram', state: 'Haryana', country: 'India', pincode: '122002',
    industry: 'Telecommunications',
    website: 'https://www.airtel.in',
    address: 'Bharti Crescent, 1 Nelson Mandela Road, Vasant Kunj Phase II',
  },
  {
    companyName: 'Tata Consultancy Services',
    contactPerson: 'Arun Krishnamurthy',
    email: 'arun.k@tcs.com',
    phone: '9888088901',
    city: 'Chennai', state: 'Tamil Nadu', country: 'India', pincode: '600096',
    industry: 'Information Technology',
    website: 'https://www.tcs.com',
    address: 'TCS House, Raveline Street, Fort',
  },
  {
    companyName: 'Bajaj Finserv Ltd',
    contactPerson: 'Deepa Joshi',
    email: 'deepa.joshi@bajajfinserv.in',
    phone: '9899099012',
    city: 'Pune', state: 'Maharashtra', country: 'India', pincode: '411045',
    industry: 'Banking & Financial Services',
    website: 'https://www.bajajfinserv.in',
    address: 'Bajaj Finserv Corporate Office, Viman Nagar',
  },
  {
    companyName: 'Asian Paints Limited',
    contactPerson: 'Manoj Tiwari',
    email: 'manoj.tiwari@asianpaints.com',
    phone: '9810109123',
    city: 'Mumbai', state: 'Maharashtra', country: 'India', pincode: '400051',
    industry: 'Manufacturing & Chemicals',
    website: 'https://www.asianpaints.com',
    address: '6A, Shantinagar, Santacruz East',
  },
];

// ── Jobs ──────────────────────────────────────────────────────────────────────
// Distribution: Infosys(3), Mahindra(3), Sun Pharma(3), HDFC(2), Reliance(2),
//               Wipro(2), Airtel(2), TCS(1), Bajaj(1), Asian Paints(1) = 20 total

const JOBS_BY_CLIENT = (clientMap: Record<string, string>) => [
  // Infosys BPM — 3 jobs
  {
    clientId: clientMap['Infosys BPM Ltd'],
    jobTitle: 'Senior Java Developer',
    description: 'We are looking for an experienced Java Developer to join our BPM team. You will design and implement high-performance Java applications for enterprise clients.',
    requiredSkills: ['Java', 'Spring Boot', 'Microservices', 'REST APIs', 'MySQL'],
    preferredSkills: ['Docker', 'Kubernetes', 'AWS', 'Kafka'],
    experienceMin: 4, experienceMax: 8,
    salaryMin: 1200000, salaryMax: 1800000,
    jobType: 'FULL_TIME', workLocation: 'Pune', workMode: 'Hybrid',
    numberOfOpenings: 3, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-07-15'),
    tags: ['java', 'backend', 'microservices'],
  },
  {
    clientId: clientMap['Infosys BPM Ltd'],
    jobTitle: 'Business Analyst – Finance Domain',
    description: 'Seeking a Business Analyst with strong finance domain knowledge to bridge the gap between business requirements and technical teams.',
    requiredSkills: ['Business Analysis', 'BRD', 'Finance Domain', 'SQL', 'JIRA'],
    preferredSkills: ['Agile', 'Tableau', 'Power BI'],
    experienceMin: 3, experienceMax: 6,
    salaryMin: 900000, salaryMax: 1400000,
    jobType: 'FULL_TIME', workLocation: 'Pune', workMode: 'On-site',
    numberOfOpenings: 2, status: 'ACTIVE', priority: 'MEDIUM',
    closingDate: new Date('2026-06-30'),
    tags: ['business-analysis', 'finance', 'bpo'],
  },
  {
    clientId: clientMap['Infosys BPM Ltd'],
    jobTitle: 'DevOps Engineer',
    description: 'Join our infrastructure team to automate and streamline CI/CD pipelines, manage cloud infrastructure, and drive DevOps best practices.',
    requiredSkills: ['Docker', 'Kubernetes', 'Jenkins', 'Linux', 'AWS'],
    preferredSkills: ['Terraform', 'Ansible', 'Prometheus'],
    experienceMin: 3, experienceMax: 7,
    salaryMin: 1100000, salaryMax: 1700000,
    jobType: 'FULL_TIME', workLocation: 'Pune', workMode: 'Hybrid',
    numberOfOpenings: 2, status: 'ACTIVE', priority: 'URGENT',
    closingDate: new Date('2026-06-20'),
    tags: ['devops', 'cloud', 'infrastructure'],
  },

  // Mahindra & Mahindra — 3 jobs
  {
    clientId: clientMap['Mahindra & Mahindra Ltd'],
    jobTitle: 'Mechanical Design Engineer – EV',
    description: 'Work on the next generation of electric vehicles. Responsible for CAD design, tolerance analysis, and DFM reviews for EV powertrain components.',
    requiredSkills: ['CATIA', 'GD&T', 'Automotive Design', 'CAE', 'SolidWorks'],
    preferredSkills: ['EV Powertrain', 'ANSYS', 'DFMEA'],
    experienceMin: 2, experienceMax: 5,
    salaryMin: 800000, salaryMax: 1300000,
    jobType: 'FULL_TIME', workLocation: 'Mumbai', workMode: 'On-site',
    numberOfOpenings: 4, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-07-31'),
    tags: ['mechanical', 'ev', 'automotive'],
  },
  {
    clientId: clientMap['Mahindra & Mahindra Ltd'],
    jobTitle: 'Supply Chain Manager',
    description: 'Lead end-to-end supply chain operations for the automotive division. Drive vendor development, logistics optimization, and inventory management.',
    requiredSkills: ['Supply Chain Management', 'Vendor Development', 'SAP MM', 'Logistics', 'Inventory Management'],
    preferredSkills: ['Six Sigma', 'Lean Manufacturing', 'Power BI'],
    experienceMin: 6, experienceMax: 12,
    salaryMin: 1800000, salaryMax: 2800000,
    jobType: 'FULL_TIME', workLocation: 'Nashik', workMode: 'On-site',
    numberOfOpenings: 1, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-06-25'),
    tags: ['supply-chain', 'operations', 'automotive'],
  },
  {
    clientId: clientMap['Mahindra & Mahindra Ltd'],
    jobTitle: 'Embedded Software Engineer',
    description: 'Develop embedded software for vehicle ECUs and control systems. Work closely with hardware teams on CAN, LIN, and Ethernet protocols.',
    requiredSkills: ['C/C++', 'Embedded C', 'AUTOSAR', 'CAN Bus', 'MISRA-C'],
    preferredSkills: ['Python', 'Vector tools', 'MATLAB Simulink'],
    experienceMin: 3, experienceMax: 7,
    salaryMin: 1000000, salaryMax: 1600000,
    jobType: 'FULL_TIME', workLocation: 'Pune', workMode: 'On-site',
    numberOfOpenings: 3, status: 'ACTIVE', priority: 'MEDIUM',
    closingDate: new Date('2026-08-15'),
    tags: ['embedded', 'automotive', 'software'],
  },

  // Sun Pharma — 3 jobs
  {
    clientId: clientMap['Sun Pharmaceutical Industries'],
    jobTitle: 'QA Manager – Pharmaceutical',
    description: 'Responsible for maintaining quality management systems, overseeing batch release, managing regulatory inspections and CAPA processes.',
    requiredSkills: ['GMP', 'Quality Assurance', 'Regulatory Affairs', 'CAPA', 'FDA Compliance'],
    preferredSkills: ['ICH Guidelines', 'Validation', 'SAP QM'],
    experienceMin: 7, experienceMax: 14,
    salaryMin: 2000000, salaryMax: 3200000,
    jobType: 'FULL_TIME', workLocation: 'Mumbai', workMode: 'On-site',
    numberOfOpenings: 1, status: 'ACTIVE', priority: 'URGENT',
    closingDate: new Date('2026-06-15'),
    tags: ['pharma', 'quality', 'gmp'],
  },
  {
    clientId: clientMap['Sun Pharmaceutical Industries'],
    jobTitle: 'Medical Representative – Mumbai Region',
    description: 'Promote Sun Pharma specialty products to doctors, hospitals, and healthcare professionals across the Mumbai region. Drive prescription growth and market share.',
    requiredSkills: ['Sales', 'Pharma Knowledge', 'Doctor Detailing', 'Territory Management', 'Communication'],
    preferredSkills: ['CRM Tools', 'Oncology Knowledge'],
    experienceMin: 1, experienceMax: 4,
    salaryMin: 350000, salaryMax: 600000,
    jobType: 'FULL_TIME', workLocation: 'Mumbai', workMode: 'Field Work',
    numberOfOpenings: 8, status: 'ACTIVE', priority: 'MEDIUM',
    closingDate: new Date('2026-07-10'),
    tags: ['pharma-sales', 'medical-rep', 'mumbai'],
  },
  {
    clientId: clientMap['Sun Pharmaceutical Industries'],
    jobTitle: 'Formulation Scientist – R&D',
    description: 'Develop and optimize pharmaceutical formulations for oral solid dosage forms. Conduct pre-formulation studies, stability testing, and scale-up activities.',
    requiredSkills: ['Formulation Development', 'Preformulation', 'Stability Testing', 'HPLC', 'Analytical Chemistry'],
    preferredSkills: ['Design of Experiments', 'Dissolution Testing', 'GMP Labs'],
    experienceMin: 3, experienceMax: 8,
    salaryMin: 800000, salaryMax: 1400000,
    jobType: 'FULL_TIME', workLocation: 'Vadodara', workMode: 'On-site',
    numberOfOpenings: 2, status: 'ON_HOLD', priority: 'MEDIUM',
    closingDate: new Date('2026-09-01'),
    tags: ['formulation', 'rd', 'pharma'],
  },

  // HDFC Bank — 2 jobs
  {
    clientId: clientMap['HDFC Bank Limited'],
    jobTitle: 'Relationship Manager – SME Banking',
    description: 'Acquire and manage SME banking relationships. Responsible for achieving business targets through working capital loans, trade finance, and current account acquisition.',
    requiredSkills: ['SME Banking', 'Credit Analysis', 'Sales', 'Financial Products', 'Relationship Management'],
    preferredSkills: ['Trade Finance', 'Cash Management', 'Treasury'],
    experienceMin: 3, experienceMax: 8,
    salaryMin: 700000, salaryMax: 1200000,
    jobType: 'FULL_TIME', workLocation: 'Mumbai', workMode: 'On-site',
    numberOfOpenings: 5, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-06-28'),
    tags: ['banking', 'sme', 'relationship-manager'],
  },
  {
    clientId: clientMap['HDFC Bank Limited'],
    jobTitle: 'Data Scientist – Risk Analytics',
    description: 'Build machine learning models for credit risk scoring, fraud detection, and early warning systems. Work with large-scale transaction datasets.',
    requiredSkills: ['Python', 'Machine Learning', 'SQL', 'Statistical Modeling', 'Risk Management'],
    preferredSkills: ['PySpark', 'AWS', 'Deep Learning', 'XGBoost'],
    experienceMin: 3, experienceMax: 7,
    salaryMin: 1400000, salaryMax: 2200000,
    jobType: 'FULL_TIME', workLocation: 'Mumbai', workMode: 'Hybrid',
    numberOfOpenings: 2, status: 'ACTIVE', priority: 'URGENT',
    closingDate: new Date('2026-07-05'),
    tags: ['data-science', 'risk', 'banking'],
  },

  // Reliance Retail — 2 jobs
  {
    clientId: clientMap['Reliance Retail Ventures Ltd'],
    jobTitle: 'Category Manager – Electronics',
    description: 'Own and drive the electronics category P&L. Responsible for vendor negotiations, assortment planning, pricing strategy, and promotional campaigns.',
    requiredSkills: ['Category Management', 'Vendor Negotiation', 'P&L Management', 'Retail Analytics', 'Merchandising'],
    preferredSkills: ['SAP', 'Advanced Excel', 'Consumer Electronics Domain'],
    experienceMin: 5, experienceMax: 10,
    salaryMin: 1600000, salaryMax: 2500000,
    jobType: 'FULL_TIME', workLocation: 'Mumbai', workMode: 'On-site',
    numberOfOpenings: 1, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-07-20'),
    tags: ['retail', 'category', 'electronics'],
  },
  {
    clientId: clientMap['Reliance Retail Ventures Ltd'],
    jobTitle: 'Store Operations Manager',
    description: 'Oversee daily store operations for a high-volume retail format. Manage store teams, inventory, shrinkage control, visual merchandising, and customer experience metrics.',
    requiredSkills: ['Retail Operations', 'Team Management', 'Inventory Control', 'Customer Service', 'P&L'],
    preferredSkills: ['Retail SIS', 'Loss Prevention', 'Visual Merchandising'],
    experienceMin: 4, experienceMax: 9,
    salaryMin: 900000, salaryMax: 1500000,
    jobType: 'FULL_TIME', workLocation: 'Pune', workMode: 'On-site',
    numberOfOpenings: 3, status: 'ACTIVE', priority: 'MEDIUM',
    closingDate: new Date('2026-08-01'),
    tags: ['retail', 'store-ops', 'management'],
  },

  // Wipro — 2 jobs
  {
    clientId: clientMap['Wipro Technologies'],
    jobTitle: 'Cloud Solutions Architect',
    description: 'Design and implement large-scale cloud architectures on AWS and Azure for enterprise customers. Lead cloud migration programs and define best-practice governance frameworks.',
    requiredSkills: ['AWS', 'Azure', 'Cloud Architecture', 'Terraform', 'Security'],
    preferredSkills: ['GCP', 'FinOps', 'DevSecOps', 'Solution Selling'],
    experienceMin: 8, experienceMax: 15,
    salaryMin: 2800000, salaryMax: 4500000,
    jobType: 'FULL_TIME', workLocation: 'Bengaluru', workMode: 'Hybrid',
    numberOfOpenings: 2, status: 'ACTIVE', priority: 'URGENT',
    closingDate: new Date('2026-06-18'),
    tags: ['cloud', 'architecture', 'aws', 'azure'],
  },
  {
    clientId: clientMap['Wipro Technologies'],
    jobTitle: 'Full Stack Developer – React & Node',
    description: 'Build scalable web applications for global clients. Work on front-end with React and back-end with Node.js/Express, deploying on AWS.',
    requiredSkills: ['React', 'Node.js', 'TypeScript', 'REST APIs', 'PostgreSQL'],
    preferredSkills: ['GraphQL', 'Redis', 'Docker', 'Next.js'],
    experienceMin: 3, experienceMax: 7,
    salaryMin: 1100000, salaryMax: 1900000,
    jobType: 'FULL_TIME', workLocation: 'Bengaluru', workMode: 'Hybrid',
    numberOfOpenings: 5, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-07-25'),
    tags: ['fullstack', 'react', 'nodejs'],
  },

  // Airtel — 2 jobs
  {
    clientId: clientMap['Airtel Business'],
    jobTitle: 'Enterprise Sales Manager – B2B',
    description: 'Drive enterprise telecom and cloud solutions sales to large corporates and government accounts. Own the complete sales cycle from prospecting to closure.',
    requiredSkills: ['B2B Sales', 'Enterprise Sales', 'Telecom Products', 'Account Management', 'CRM'],
    preferredSkills: ['Cloud Sales', 'MPLS', 'SD-WAN', 'Salesforce'],
    experienceMin: 5, experienceMax: 12,
    salaryMin: 1500000, salaryMax: 2500000,
    jobType: 'FULL_TIME', workLocation: 'Gurugram', workMode: 'On-site',
    numberOfOpenings: 4, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-07-08'),
    tags: ['sales', 'enterprise', 'telecom'],
  },
  {
    clientId: clientMap['Airtel Business'],
    jobTitle: 'Network Operations Engineer',
    description: 'Monitor and maintain core network infrastructure. Respond to network incidents, perform root cause analysis, and drive capacity planning activities.',
    requiredSkills: ['CCNA', 'Network Monitoring', 'BGP', 'MPLS', 'Incident Management'],
    preferredSkills: ['Cisco NSO', 'Python scripting', 'ITIL', '5G NR'],
    experienceMin: 2, experienceMax: 6,
    salaryMin: 600000, salaryMax: 1000000,
    jobType: 'FULL_TIME', workLocation: 'Delhi', workMode: 'On-site',
    numberOfOpenings: 6, status: 'ACTIVE', priority: 'MEDIUM',
    closingDate: new Date('2026-08-10'),
    tags: ['network', 'telecom', 'noc'],
  },

  // TCS — 1 job
  {
    clientId: clientMap['Tata Consultancy Services'],
    jobTitle: 'SAP FICO Consultant',
    description: 'Implement and support SAP FICO modules for a large manufacturing client. Handle configuration, customization, user training, and go-live support.',
    requiredSkills: ['SAP FICO', 'Finance', 'Accounts Payable', 'Accounts Receivable', 'General Ledger'],
    preferredSkills: ['S/4HANA', 'SAP BPC', 'ABAP Basics', 'Project Accounting'],
    experienceMin: 4, experienceMax: 9,
    salaryMin: 1100000, salaryMax: 1900000,
    jobType: 'FULL_TIME', workLocation: 'Chennai', workMode: 'On-site',
    numberOfOpenings: 2, status: 'ACTIVE', priority: 'HIGH',
    closingDate: new Date('2026-07-30'),
    tags: ['sap', 'fico', 'consulting'],
  },

  // Bajaj Finserv — 1 job
  {
    clientId: clientMap['Bajaj Finserv Ltd'],
    jobTitle: 'Credit Risk Analyst',
    description: 'Analyse and manage credit risk for personal and business loan portfolios. Build and validate risk scorecards, monitor portfolio health, and recommend policy changes.',
    requiredSkills: ['Credit Risk', 'SAS/R/Python', 'Statistical Modeling', 'NBFC', 'Excel'],
    preferredSkills: ['Machine Learning', 'SQL', 'Power BI', 'Basel Norms'],
    experienceMin: 2, experienceMax: 6,
    salaryMin: 750000, salaryMax: 1300000,
    jobType: 'FULL_TIME', workLocation: 'Pune', workMode: 'Hybrid',
    numberOfOpenings: 3, status: 'ACTIVE', priority: 'MEDIUM',
    closingDate: new Date('2026-08-20'),
    tags: ['credit-risk', 'fintech', 'analytics'],
  },

  // Asian Paints — 1 job
  {
    clientId: clientMap['Asian Paints Limited'],
    jobTitle: 'Territory Sales Executive',
    description: 'Responsible for achieving primary and secondary sales targets for Asian Paints products in the assigned territory. Manage dealer network, distributor relationships, and drive paint schemes.',
    requiredSkills: ['Field Sales', 'Dealer Management', 'Channel Sales', 'Paint Knowledge', 'Communication'],
    preferredSkills: ['Construction Chemicals', 'B2B Relationships', 'CRM'],
    experienceMin: 1, experienceMax: 4,
    salaryMin: 300000, salaryMax: 550000,
    jobType: 'FULL_TIME', workLocation: 'Mumbai', workMode: 'Field Work',
    numberOfOpenings: 10, status: 'ACTIVE', priority: 'LOW',
    closingDate: new Date('2026-09-15'),
    tags: ['sales', 'field', 'paints'],
  },
];

// ── Candidates ────────────────────────────────────────────────────────────────

const CANDIDATES = [
  {
    firstName: 'Arjun', lastName: 'Sharma', gender: 'MALE' as const,
    email: 'arjun.sharma@gmail.com', phone: '9876543210',
    dateOfBirth: new Date('1993-04-12'),
    currentLocation: 'Pune', city: 'Pune', state: 'Maharashtra',
    currentDesignation: 'Senior Java Developer', currentCompany: 'Capgemini',
    totalExperience: 6.5, currentCTC: 1100000, expectedCTC: 1500000, noticePeriod: 30,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'Pune University', passingYear: 2015,
    skills: ['Java', 'Spring Boot', 'Microservices', 'MySQL', 'REST APIs'],
    technologyStack: ['Java 11', 'Spring Boot 3', 'Docker', 'Kubernetes'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Priya', lastName: 'Mehta', gender: 'FEMALE' as const,
    email: 'priya.mehta@yahoo.com', phone: '9765432109',
    dateOfBirth: new Date('1995-09-22'),
    currentLocation: 'Mumbai', city: 'Mumbai', state: 'Maharashtra',
    currentDesignation: 'Business Analyst', currentCompany: 'Accenture',
    totalExperience: 4.0, currentCTC: 900000, expectedCTC: 1200000, noticePeriod: 45,
    highestQualification: 'MBA', specialization: 'Finance', university: 'Symbiosis International University', passingYear: 2017,
    skills: ['Business Analysis', 'SQL', 'JIRA', 'BRD', 'Agile'],
    technologyStack: ['JIRA', 'Confluence', 'MS Visio', 'Tableau'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Rohit', lastName: 'Verma', gender: 'MALE' as const,
    email: 'rohit.verma@gmail.com', phone: '9654321098',
    dateOfBirth: new Date('1990-07-05'),
    currentLocation: 'Bengaluru', city: 'Bengaluru', state: 'Karnataka',
    currentDesignation: 'DevOps Lead', currentCompany: 'Thoughtworks',
    totalExperience: 9.0, currentCTC: 2200000, expectedCTC: 2800000, noticePeriod: 60,
    highestQualification: 'B.E.', specialization: 'Electronics & Communication', university: 'VTU', passingYear: 2012,
    skills: ['Docker', 'Kubernetes', 'Jenkins', 'AWS', 'Terraform', 'Ansible'],
    technologyStack: ['AWS EKS', 'ArgoCD', 'Prometheus', 'Grafana'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Sneha', lastName: 'Kulkarni', gender: 'FEMALE' as const,
    email: 'sneha.kulkarni@outlook.com', phone: '9543210987',
    dateOfBirth: new Date('1997-02-14'),
    currentLocation: 'Pune', city: 'Pune', state: 'Maharashtra',
    currentDesignation: 'Mechanical Design Engineer', currentCompany: 'Tata AutoComp',
    totalExperience: 2.5, currentCTC: 550000, expectedCTC: 800000, noticePeriod: 30,
    highestQualification: 'B.E.', specialization: 'Mechanical Engineering', university: 'Savitribai Phule Pune University', passingYear: 2019,
    skills: ['CATIA', 'GD&T', 'AutoCAD', 'SolidWorks'],
    technologyStack: ['CATIA V5', 'ANSYS Workbench'],
    status: 'NEW',
  },
  {
    firstName: 'Kiran', lastName: 'Patil', gender: 'MALE' as const,
    email: 'kiran.patil@gmail.com', phone: '9432109876',
    dateOfBirth: new Date('1988-11-30'),
    currentLocation: 'Nashik', city: 'Nashik', state: 'Maharashtra',
    currentDesignation: 'Supply Chain Manager', currentCompany: 'Bharat Forge',
    totalExperience: 12.0, currentCTC: 2600000, expectedCTC: 3200000, noticePeriod: 90,
    highestQualification: 'MBA', specialization: 'Operations & Supply Chain', university: 'IIM Nagpur', passingYear: 2010,
    skills: ['Supply Chain Management', 'SAP MM', 'Vendor Development', 'Logistics', 'Six Sigma'],
    technologyStack: ['SAP ERP', 'Power BI', 'Advanced Excel'],
    status: 'OFFERED',
  },
  {
    firstName: 'Ananya', lastName: 'Nair', gender: 'FEMALE' as const,
    email: 'ananya.nair@gmail.com', phone: '9321098765',
    dateOfBirth: new Date('1994-06-18'),
    currentLocation: 'Mumbai', city: 'Mumbai', state: 'Maharashtra',
    currentDesignation: 'QA Manager', currentCompany: 'Cipla',
    totalExperience: 7.5, currentCTC: 1800000, expectedCTC: 2400000, noticePeriod: 60,
    highestQualification: 'M.Pharm', specialization: 'Pharmaceutical Quality Assurance', university: 'Mumbai University', passingYear: 2014,
    skills: ['GMP', 'Quality Assurance', 'CAPA', 'FDA Compliance', 'Regulatory Affairs'],
    technologyStack: ['SAP QM', 'TrackWise', 'Veeva Vault'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Rahul', lastName: 'Singh', gender: 'MALE' as const,
    email: 'rahul.singh@rediffmail.com', phone: '9210987654',
    dateOfBirth: new Date('1996-03-07'),
    currentLocation: 'Mumbai', city: 'Mumbai', state: 'Maharashtra',
    currentDesignation: 'Medical Representative', currentCompany: 'Dr. Reddy\'s',
    totalExperience: 2.0, currentCTC: 380000, expectedCTC: 520000, noticePeriod: 30,
    highestQualification: 'B.Pharm', specialization: 'Pharmacy', university: 'Mumbai University', passingYear: 2020,
    skills: ['Doctor Detailing', 'Pharma Sales', 'Territory Management', 'Communication'],
    technologyStack: ['CRM tools', 'MS Office'],
    status: 'NEW',
  },
  {
    firstName: 'Deepa', lastName: 'Joshi', gender: 'FEMALE' as const,
    email: 'deepa.joshi@gmail.com', phone: '9109876543',
    dateOfBirth: new Date('1991-12-25'),
    currentLocation: 'Mumbai', city: 'Mumbai', state: 'Maharashtra',
    currentDesignation: 'Relationship Manager', currentCompany: 'ICICI Bank',
    totalExperience: 8.0, currentCTC: 1100000, expectedCTC: 1400000, noticePeriod: 30,
    highestQualification: 'MBA', specialization: 'Finance & Banking', university: 'Narsee Monjee', passingYear: 2013,
    skills: ['SME Banking', 'Credit Analysis', 'Sales', 'Financial Products', 'Relationship Management'],
    technologyStack: ['Finacle', 'CRM', 'MS Excel'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Vikash', lastName: 'Kumar', gender: 'MALE' as const,
    email: 'vikash.kumar@gmail.com', phone: '9098765432',
    dateOfBirth: new Date('1993-08-10'),
    currentLocation: 'Mumbai', city: 'Mumbai', state: 'Maharashtra',
    currentDesignation: 'Data Scientist', currentCompany: 'ZestMoney',
    totalExperience: 5.0, currentCTC: 1600000, expectedCTC: 2100000, noticePeriod: 45,
    highestQualification: 'M.Tech', specialization: 'Data Science', university: 'IIT Bombay', passingYear: 2016,
    skills: ['Python', 'Machine Learning', 'SQL', 'Statistical Modeling', 'XGBoost'],
    technologyStack: ['Python', 'Scikit-learn', 'PySpark', 'AWS SageMaker'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Pooja', lastName: 'Iyer', gender: 'FEMALE' as const,
    email: 'pooja.iyer@gmail.com', phone: '9987654321',
    dateOfBirth: new Date('1995-05-03'),
    currentLocation: 'Bengaluru', city: 'Bengaluru', state: 'Karnataka',
    currentDesignation: 'Cloud Solutions Architect', currentCompany: 'HCL Technologies',
    totalExperience: 7.0, currentCTC: 2800000, expectedCTC: 3800000, noticePeriod: 60,
    highestQualification: 'B.Tech', specialization: 'Information Technology', university: 'Anna University', passingYear: 2015,
    skills: ['AWS', 'Azure', 'Terraform', 'Cloud Architecture', 'DevSecOps'],
    technologyStack: ['AWS', 'Azure', 'Terraform', 'Kubernetes', 'Jenkins'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Suresh', lastName: 'Reddy', gender: 'MALE' as const,
    email: 'suresh.reddy@gmail.com', phone: '9876012345',
    dateOfBirth: new Date('1992-01-17'),
    currentLocation: 'Hyderabad', city: 'Hyderabad', state: 'Telangana',
    currentDesignation: 'Full Stack Developer', currentCompany: 'Tech Mahindra',
    totalExperience: 5.5, currentCTC: 1300000, expectedCTC: 1800000, noticePeriod: 30,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'JNTU Hyderabad', passingYear: 2015,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'REST APIs'],
    technologyStack: ['React 18', 'Node.js', 'PostgreSQL', 'Docker', 'AWS'],
    status: 'NEW',
  },
  {
    firstName: 'Nisha', lastName: 'Gupta', gender: 'FEMALE' as const,
    email: 'nisha.gupta@gmail.com', phone: '9765012340',
    dateOfBirth: new Date('1994-10-28'),
    currentLocation: 'Delhi', city: 'New Delhi', state: 'Delhi',
    currentDesignation: 'Enterprise Sales Manager', currentCompany: 'Vodafone Idea',
    totalExperience: 6.5, currentCTC: 1400000, expectedCTC: 2000000, noticePeriod: 45,
    highestQualification: 'MBA', specialization: 'Marketing & Sales', university: 'Delhi University', passingYear: 2014,
    skills: ['B2B Sales', 'Enterprise Sales', 'Telecom Products', 'Account Management', 'CRM'],
    technologyStack: ['Salesforce', 'MS Dynamics', 'Excel'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Amit', lastName: 'Sharma', gender: 'MALE' as const,
    email: 'amit.sharma92@gmail.com', phone: '9654012342',
    dateOfBirth: new Date('1992-07-20'),
    currentLocation: 'Delhi', city: 'New Delhi', state: 'Delhi',
    currentDesignation: 'Network Operations Engineer', currentCompany: 'BSNL',
    totalExperience: 4.5, currentCTC: 680000, expectedCTC: 900000, noticePeriod: 30,
    highestQualification: 'B.E.', specialization: 'Electronics & Telecommunication', university: 'Delhi Technological University', passingYear: 2016,
    skills: ['CCNA', 'Network Monitoring', 'BGP', 'MPLS', 'Incident Management'],
    technologyStack: ['Cisco IOS', 'PRTG', 'Wireshark', 'Linux'],
    status: 'SCREENING',
  },
  {
    firstName: 'Kavitha', lastName: 'Sundaram', gender: 'FEMALE' as const,
    email: 'kavitha.s@gmail.com', phone: '9543012343',
    dateOfBirth: new Date('1991-03-14'),
    currentLocation: 'Chennai', city: 'Chennai', state: 'Tamil Nadu',
    currentDesignation: 'SAP FICO Consultant', currentCompany: 'Deloitte',
    totalExperience: 8.5, currentCTC: 1900000, expectedCTC: 2600000, noticePeriod: 60,
    highestQualification: 'B.Com', specialization: 'Finance & Accounting', university: 'University of Madras', passingYear: 2012,
    skills: ['SAP FICO', 'Finance', 'Accounts Payable', 'General Ledger', 'S/4HANA'],
    technologyStack: ['SAP S/4HANA', 'SAP BPC', 'SAP ERP'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Sanjay', lastName: 'Bhat', gender: 'MALE' as const,
    email: 'sanjay.bhat@gmail.com', phone: '9432012344',
    dateOfBirth: new Date('1989-09-09'),
    currentLocation: 'Pune', city: 'Pune', state: 'Maharashtra',
    currentDesignation: 'Credit Risk Analyst', currentCompany: 'CRISIL',
    totalExperience: 10.0, currentCTC: 1500000, expectedCTC: 1900000, noticePeriod: 60,
    highestQualification: 'MBA', specialization: 'Finance', university: 'IIM Kozhikode', passingYear: 2011,
    skills: ['Credit Risk', 'Python', 'Statistical Modeling', 'NBFC', 'Excel'],
    technologyStack: ['Python', 'SAS', 'Power BI', 'SQL'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Meera', lastName: 'Pillai', gender: 'FEMALE' as const,
    email: 'meera.pillai@gmail.com', phone: '9321012345',
    dateOfBirth: new Date('1996-06-01'),
    currentLocation: 'Mumbai', city: 'Mumbai', state: 'Maharashtra',
    currentDesignation: 'Territory Sales Executive', currentCompany: 'Asian Paints',
    totalExperience: 2.0, currentCTC: 310000, expectedCTC: 450000, noticePeriod: 30,
    highestQualification: 'B.Com', specialization: 'Marketing', university: 'University of Mumbai', passingYear: 2020,
    skills: ['Field Sales', 'Dealer Management', 'Channel Sales', 'Communication'],
    technologyStack: ['MS Office', 'CRM'],
    status: 'NEW',
  },
  {
    firstName: 'Akash', lastName: 'Pandey', gender: 'MALE' as const,
    email: 'akash.pandey@gmail.com', phone: '9210012346',
    dateOfBirth: new Date('1993-11-11'),
    currentLocation: 'Lucknow', city: 'Lucknow', state: 'Uttar Pradesh',
    currentDesignation: 'Embedded Software Engineer', currentCompany: 'Bosch',
    totalExperience: 5.0, currentCTC: 1100000, expectedCTC: 1500000, noticePeriod: 30,
    highestQualification: 'B.Tech', specialization: 'Electronics Engineering', university: 'UPTU', passingYear: 2016,
    skills: ['C/C++', 'Embedded C', 'AUTOSAR', 'CAN Bus', 'MISRA-C'],
    technologyStack: ['AUTOSAR', 'Vector CANoe', 'MATLAB Simulink'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Ritu', lastName: 'Agarwal', gender: 'FEMALE' as const,
    email: 'ritu.agarwal@hotmail.com', phone: '9109012347',
    dateOfBirth: new Date('1990-02-28'),
    currentLocation: 'Jaipur', city: 'Jaipur', state: 'Rajasthan',
    currentDesignation: 'Formulation Scientist', currentCompany: 'Lupin',
    totalExperience: 7.0, currentCTC: 950000, expectedCTC: 1300000, noticePeriod: 45,
    highestQualification: 'M.Pharm', specialization: 'Pharmaceutics', university: 'Rajasthan University', passingYear: 2013,
    skills: ['Formulation Development', 'Stability Testing', 'HPLC', 'Analytical Chemistry'],
    technologyStack: ['Empower', 'LIMS', 'MS Office'],
    status: 'SCREENING',
  },
  {
    firstName: 'Nikhil', lastName: 'Desai', gender: 'MALE' as const,
    email: 'nikhil.desai@gmail.com', phone: '9098012348',
    dateOfBirth: new Date('1994-04-22'),
    currentLocation: 'Pune', city: 'Pune', state: 'Maharashtra',
    currentDesignation: 'Category Manager', currentCompany: 'BigBasket',
    totalExperience: 5.0, currentCTC: 1400000, expectedCTC: 1900000, noticePeriod: 45,
    highestQualification: 'MBA', specialization: 'Marketing & Operations', university: 'SP Jain', passingYear: 2017,
    skills: ['Category Management', 'Vendor Negotiation', 'P&L Management', 'Retail Analytics'],
    technologyStack: ['SAP', 'Advanced Excel', 'Tableau', 'Power BI'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Priyanka', lastName: 'Rao', gender: 'FEMALE' as const,
    email: 'priyanka.rao@gmail.com', phone: '9987012349',
    dateOfBirth: new Date('1995-08-14'),
    currentLocation: 'Bengaluru', city: 'Bengaluru', state: 'Karnataka',
    currentDesignation: 'Store Manager', currentCompany: 'Shoppers Stop',
    totalExperience: 4.5, currentCTC: 900000, expectedCTC: 1300000, noticePeriod: 30,
    highestQualification: 'B.Com', specialization: 'Retail Management', university: 'Bangalore University', passingYear: 2018,
    skills: ['Retail Operations', 'Team Management', 'Inventory Control', 'Customer Service'],
    technologyStack: ['RetailPro', 'SAP Retail'],
    status: 'NEW',
  },
  {
    firstName: 'Harish', lastName: 'Menon', gender: 'MALE' as const,
    email: 'harish.menon@gmail.com', phone: '9865012350',
    dateOfBirth: new Date('1988-05-17'),
    currentLocation: 'Kochi', city: 'Kochi', state: 'Kerala',
    currentDesignation: 'Senior Software Architect', currentCompany: 'UST Global',
    totalExperience: 13.0, currentCTC: 3200000, expectedCTC: 4000000, noticePeriod: 90,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'Cochin University', passingYear: 2009,
    skills: ['Java', 'Spring Boot', 'Microservices', 'AWS', 'System Design'],
    technologyStack: ['Java 17', 'Spring Cloud', 'Kafka', 'MongoDB', 'AWS'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Swathi', lastName: 'Krishnan', gender: 'FEMALE' as const,
    email: 'swathi.krishnan@gmail.com', phone: '9754012351',
    dateOfBirth: new Date('1997-01-08'),
    currentLocation: 'Chennai', city: 'Chennai', state: 'Tamil Nadu',
    currentDesignation: 'React Developer', currentCompany: 'Freshworks',
    totalExperience: 3.0, currentCTC: 900000, expectedCTC: 1300000, noticePeriod: 30,
    highestQualification: 'B.E.', specialization: 'Computer Science', university: 'Anna University', passingYear: 2020,
    skills: ['React', 'TypeScript', 'CSS', 'Node.js', 'REST APIs'],
    technologyStack: ['React 18', 'Tailwind CSS', 'GraphQL', 'Vite'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Gaurav', lastName: 'Mishra', gender: 'MALE' as const,
    email: 'gaurav.mishra@gmail.com', phone: '9643012352',
    dateOfBirth: new Date('1991-07-23'),
    currentLocation: 'Bhopal', city: 'Bhopal', state: 'Madhya Pradesh',
    currentDesignation: 'Network Security Engineer', currentCompany: 'HCL',
    totalExperience: 7.0, currentCTC: 1100000, expectedCTC: 1500000, noticePeriod: 45,
    highestQualification: 'B.Tech', specialization: 'Information Security', university: 'RGPV', passingYear: 2014,
    skills: ['Network Security', 'Firewall', 'SIEM', 'Ethical Hacking', 'Python'],
    technologyStack: ['Palo Alto', 'Splunk', 'Nessus', 'Wireshark'],
    status: 'SCREENING',
  },
  {
    firstName: 'Lakshmi', lastName: 'Subramaniam', gender: 'FEMALE' as const,
    email: 'lakshmi.sub@gmail.com', phone: '9532012353',
    dateOfBirth: new Date('1993-12-05'),
    currentLocation: 'Coimbatore', city: 'Coimbatore', state: 'Tamil Nadu',
    currentDesignation: 'HR Manager', currentCompany: 'TVS Motor Company',
    totalExperience: 7.5, currentCTC: 1200000, expectedCTC: 1700000, noticePeriod: 60,
    highestQualification: 'MBA', specialization: 'Human Resources', university: 'PSG College of Technology', passingYear: 2013,
    skills: ['Talent Acquisition', 'HRBP', 'Performance Management', 'Employee Relations'],
    technologyStack: ['SAP HR', 'Workday', 'Keka'],
    status: 'NEW',
  },
  {
    firstName: 'Rajiv', lastName: 'Tiwari', gender: 'MALE' as const,
    email: 'rajiv.tiwari@gmail.com', phone: '9421012354',
    dateOfBirth: new Date('1990-09-14'),
    currentLocation: 'Varanasi', city: 'Varanasi', state: 'Uttar Pradesh',
    currentDesignation: 'Project Manager – IT', currentCompany: 'Mphasis',
    totalExperience: 10.5, currentCTC: 2200000, expectedCTC: 2900000, noticePeriod: 60,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'IIT BHU', passingYear: 2012,
    skills: ['Project Management', 'Agile', 'JIRA', 'Stakeholder Management', 'Budget Management'],
    technologyStack: ['JIRA', 'MS Project', 'Confluence', 'Slack'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Shalini', lastName: 'Kapoor', gender: 'FEMALE' as const,
    email: 'shalini.kapoor@gmail.com', phone: '9310012355',
    dateOfBirth: new Date('1996-04-19'),
    currentLocation: 'Chandigarh', city: 'Chandigarh', state: 'Punjab',
    currentDesignation: 'Content Writer & SEO Specialist', currentCompany: 'Naukri.com',
    totalExperience: 3.5, currentCTC: 550000, expectedCTC: 800000, noticePeriod: 30,
    highestQualification: 'BA', specialization: 'English Literature', university: 'Panjab University', passingYear: 2018,
    skills: ['Content Writing', 'SEO', 'Digital Marketing', 'Copywriting', 'WordPress'],
    technologyStack: ['WordPress', 'SEMrush', 'Google Analytics'],
    status: 'NEW',
  },
  {
    firstName: 'Aditya', lastName: 'Banerjee', gender: 'MALE' as const,
    email: 'aditya.banerjee@gmail.com', phone: '9209012356',
    dateOfBirth: new Date('1992-06-30'),
    currentLocation: 'Kolkata', city: 'Kolkata', state: 'West Bengal',
    currentDesignation: 'Accounts Manager', currentCompany: 'PwC',
    totalExperience: 8.0, currentCTC: 1600000, expectedCTC: 2200000, noticePeriod: 45,
    highestQualification: 'CA', specialization: 'Chartered Accountancy', university: 'ICAI', passingYear: 2013,
    skills: ['Financial Reporting', 'Taxation', 'Audit', 'IFRS', 'SAP FICO'],
    technologyStack: ['SAP', 'Tally', 'Advanced Excel', 'Power BI'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Divya', lastName: 'Ramesh', gender: 'FEMALE' as const,
    email: 'divya.ramesh@gmail.com', phone: '9098011235',
    dateOfBirth: new Date('1994-03-16'),
    currentLocation: 'Bengaluru', city: 'Bengaluru', state: 'Karnataka',
    currentDesignation: 'UX Designer', currentCompany: 'Swiggy',
    totalExperience: 5.0, currentCTC: 1300000, expectedCTC: 1800000, noticePeriod: 30,
    highestQualification: 'B.Des', specialization: 'Interaction Design', university: 'NID Ahmedabad', passingYear: 2017,
    skills: ['UI/UX Design', 'Figma', 'User Research', 'Prototyping', 'Design Systems'],
    technologyStack: ['Figma', 'Adobe XD', 'Zeplin', 'InVision'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Manish', lastName: 'Dubey', gender: 'MALE' as const,
    email: 'manish.dubey@gmail.com', phone: '9987011111',
    dateOfBirth: new Date('1991-10-03'),
    currentLocation: 'Indore', city: 'Indore', state: 'Madhya Pradesh',
    currentDesignation: 'Digital Marketing Manager', currentCompany: 'IndiaMart',
    totalExperience: 8.0, currentCTC: 1400000, expectedCTC: 1900000, noticePeriod: 45,
    highestQualification: 'MBA', specialization: 'Marketing', university: 'IIM Indore', passingYear: 2013,
    skills: ['Digital Marketing', 'SEO/SEM', 'Google Ads', 'Social Media', 'Analytics'],
    technologyStack: ['Google Analytics', 'HubSpot', 'Semrush', 'Meta Ads'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Tanvi', lastName: 'Shah', gender: 'FEMALE' as const,
    email: 'tanvi.shah@gmail.com', phone: '9876011222',
    dateOfBirth: new Date('1996-08-25'),
    currentLocation: 'Ahmedabad', city: 'Ahmedabad', state: 'Gujarat',
    currentDesignation: 'Operations Analyst', currentCompany: 'Maersk',
    totalExperience: 3.0, currentCTC: 700000, expectedCTC: 1000000, noticePeriod: 30,
    highestQualification: 'B.Com', specialization: 'Business Administration', university: 'Gujarat University', passingYear: 2019,
    skills: ['Operations Management', 'Data Analysis', 'Excel', 'Process Improvement'],
    technologyStack: ['SAP', 'Power BI', 'MS Excel', 'SQL'],
    status: 'SCREENING',
  },
  {
    firstName: 'Vivek', lastName: 'Nambiar', gender: 'MALE' as const,
    email: 'vivek.nambiar@gmail.com', phone: '9765011333',
    dateOfBirth: new Date('1989-01-14'),
    currentLocation: 'Kochi', city: 'Kochi', state: 'Kerala',
    currentDesignation: 'Regional Sales Manager', currentCompany: 'Berger Paints',
    totalExperience: 12.5, currentCTC: 2400000, expectedCTC: 3200000, noticePeriod: 60,
    highestQualification: 'MBA', specialization: 'Sales & Marketing', university: 'Kerala University', passingYear: 2009,
    skills: ['Sales Management', 'Team Leadership', 'Channel Management', 'P&L', 'Paint Industry'],
    technologyStack: ['SAP', 'Salesforce', 'Excel'],
    status: 'NEW',
  },
  {
    firstName: 'Pallavi', lastName: 'More', gender: 'FEMALE' as const,
    email: 'pallavi.more@gmail.com', phone: '9654011444',
    dateOfBirth: new Date('1993-05-31'),
    currentLocation: 'Pune', city: 'Pune', state: 'Maharashtra',
    currentDesignation: 'Python Developer', currentCompany: 'Persistent Systems',
    totalExperience: 5.5, currentCTC: 1200000, expectedCTC: 1700000, noticePeriod: 30,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'PICT', passingYear: 2016,
    skills: ['Python', 'Django', 'REST APIs', 'PostgreSQL', 'AWS Lambda'],
    technologyStack: ['Python 3.11', 'Django', 'FastAPI', 'Celery', 'AWS'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Subhash', lastName: 'Choudhury', gender: 'MALE' as const,
    email: 'subhash.choudhury@gmail.com', phone: '9543011555',
    dateOfBirth: new Date('1987-11-20'),
    currentLocation: 'Bhubaneswar', city: 'Bhubaneswar', state: 'Odisha',
    currentDesignation: 'Civil Engineer – Infrastructure', currentCompany: 'L&T Construction',
    totalExperience: 14.0, currentCTC: 2500000, expectedCTC: 3400000, noticePeriod: 90,
    highestQualification: 'B.Tech', specialization: 'Civil Engineering', university: 'NIT Rourkela', passingYear: 2009,
    skills: ['Civil Engineering', 'Project Management', 'AutoCAD', 'MS Project', 'Estimation'],
    technologyStack: ['AutoCAD', 'Primavera P6', 'MS Project'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Ranjitha', lastName: 'Gowda', gender: 'FEMALE' as const,
    email: 'ranjitha.gowda@gmail.com', phone: '9432011666',
    dateOfBirth: new Date('1995-02-12'),
    currentLocation: 'Mysuru', city: 'Mysuru', state: 'Karnataka',
    currentDesignation: 'QA Automation Engineer', currentCompany: 'Wipro',
    totalExperience: 4.0, currentCTC: 950000, expectedCTC: 1350000, noticePeriod: 30,
    highestQualification: 'B.E.', specialization: 'Information Science', university: 'VTU', passingYear: 2019,
    skills: ['Selenium', 'Java', 'TestNG', 'JIRA', 'API Testing'],
    technologyStack: ['Selenium', 'Postman', 'Jenkins', 'Git', 'Maven'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Praveen', lastName: 'Naik', gender: 'MALE' as const,
    email: 'praveen.naik@gmail.com', phone: '9321011777',
    dateOfBirth: new Date('1990-07-07'),
    currentLocation: 'Goa', city: 'Panaji', state: 'Goa',
    currentDesignation: 'Marketing Manager – Hospitality', currentCompany: 'Taj Hotels',
    totalExperience: 9.5, currentCTC: 1800000, expectedCTC: 2500000, noticePeriod: 60,
    highestQualification: 'MBA', specialization: 'Marketing & Hospitality', university: 'Goa University', passingYear: 2012,
    skills: ['Hospitality Marketing', 'Revenue Management', 'OTA Management', 'Branding'],
    technologyStack: ['Opera PMS', 'Salesforce', 'Google Analytics'],
    status: 'NEW',
  },
  {
    firstName: 'Madhuri', lastName: 'Wankhede', gender: 'FEMALE' as const,
    email: 'madhuri.wankhede@gmail.com', phone: '9210011888',
    dateOfBirth: new Date('1993-09-29'),
    currentLocation: 'Nagpur', city: 'Nagpur', state: 'Maharashtra',
    currentDesignation: 'Financial Analyst', currentCompany: 'KPMG',
    totalExperience: 6.0, currentCTC: 1300000, expectedCTC: 1800000, noticePeriod: 45,
    highestQualification: 'CA', specialization: 'Chartered Accountancy', university: 'ICAI', passingYear: 2015,
    skills: ['Financial Modeling', 'Excel', 'Valuation', 'Due Diligence', 'IFRS'],
    technologyStack: ['Advanced Excel', 'Power BI', 'Bloomberg Terminal'],
    status: 'SCREENING',
  },
  {
    firstName: 'Saurabh', lastName: 'Chavan', gender: 'MALE' as const,
    email: 'saurabh.chavan@gmail.com', phone: '9109011999',
    dateOfBirth: new Date('1994-04-04'),
    currentLocation: 'Aurangabad', city: 'Aurangabad', state: 'Maharashtra',
    currentDesignation: 'Production Engineer', currentCompany: 'Volkswagen India',
    totalExperience: 5.5, currentCTC: 900000, expectedCTC: 1300000, noticePeriod: 30,
    highestQualification: 'B.E.', specialization: 'Mechanical Engineering', university: 'BATU', passingYear: 2016,
    skills: ['Production Planning', 'Lean Manufacturing', 'CAD', 'Quality Control', 'PLC'],
    technologyStack: ['SAP PP', 'CATIA', 'AutoCAD'],
    status: 'NEW',
  },
  {
    firstName: 'Archana', lastName: 'Narayanan', gender: 'FEMALE' as const,
    email: 'archana.n@gmail.com', phone: '9098011100',
    dateOfBirth: new Date('1992-12-16'),
    currentLocation: 'Thiruvananthapuram', city: 'Thiruvananthapuram', state: 'Kerala',
    currentDesignation: 'Data Engineer', currentCompany: 'KPMG',
    totalExperience: 7.0, currentCTC: 1800000, expectedCTC: 2400000, noticePeriod: 45,
    highestQualification: 'M.Tech', specialization: 'Computer Science', university: 'Cochin University', passingYear: 2014,
    skills: ['Python', 'PySpark', 'Airflow', 'Databricks', 'SQL'],
    technologyStack: ['Apache Spark', 'Airflow', 'Azure Data Factory', 'Databricks'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Dhruv', lastName: 'Saxena', gender: 'MALE' as const,
    email: 'dhruv.saxena@gmail.com', phone: '9987011001',
    dateOfBirth: new Date('1995-10-10'),
    currentLocation: 'Noida', city: 'Noida', state: 'Uttar Pradesh',
    currentDesignation: 'Angular Developer', currentCompany: 'HCL Technologies',
    totalExperience: 4.0, currentCTC: 1000000, expectedCTC: 1400000, noticePeriod: 30,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'AKTU', passingYear: 2019,
    skills: ['Angular', 'TypeScript', 'RxJS', 'REST APIs', 'Node.js'],
    technologyStack: ['Angular 16', 'NgRx', 'Jasmine', 'Jenkins'],
    status: 'NEW',
  },
  {
    firstName: 'Ishaan', lastName: 'Chatterjee', gender: 'MALE' as const,
    email: 'ishaan.c@gmail.com', phone: '9876011002',
    dateOfBirth: new Date('1993-03-19'),
    currentLocation: 'Kolkata', city: 'Kolkata', state: 'West Bengal',
    currentDesignation: 'iOS Developer', currentCompany: 'InfoEdge',
    totalExperience: 6.5, currentCTC: 1500000, expectedCTC: 2100000, noticePeriod: 30,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'Jadavpur University', passingYear: 2014,
    skills: ['Swift', 'iOS', 'Xcode', 'CoreData', 'REST APIs'],
    technologyStack: ['Swift 5.9', 'SwiftUI', 'Combine', 'Firebase'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Bhavna', lastName: 'Trivedi', gender: 'FEMALE' as const,
    email: 'bhavna.trivedi@gmail.com', phone: '9765011003',
    dateOfBirth: new Date('1997-07-07'),
    currentLocation: 'Surat', city: 'Surat', state: 'Gujarat',
    currentDesignation: 'Junior Accountant', currentCompany: 'HDFC Securities',
    totalExperience: 2.0, currentCTC: 350000, expectedCTC: 500000, noticePeriod: 15,
    highestQualification: 'B.Com', specialization: 'Accounting & Finance', university: 'VNSGU', passingYear: 2021,
    skills: ['Tally', 'GST', 'TDS', 'Accounts Payable', 'Bank Reconciliation'],
    technologyStack: ['Tally ERP 9', 'MS Excel', 'Zoho Books'],
    status: 'NEW',
  },
  {
    firstName: 'Kartik', lastName: 'Thakur', gender: 'MALE' as const,
    email: 'kartik.thakur@gmail.com', phone: '9654011004',
    dateOfBirth: new Date('1991-05-26'),
    currentLocation: 'Shimla', city: 'Shimla', state: 'Himachal Pradesh',
    currentDesignation: 'Network Administrator', currentCompany: 'BSNL',
    totalExperience: 8.5, currentCTC: 950000, expectedCTC: 1300000, noticePeriod: 60,
    highestQualification: 'B.Tech', specialization: 'IT Networking', university: 'HP University', passingYear: 2013,
    skills: ['Network Administration', 'Cisco', 'Linux', 'VLANS', 'Firewalls'],
    technologyStack: ['Cisco IOS', 'pfSense', 'Zabbix', 'Linux'],
    status: 'SCREENING',
  },
  {
    firstName: 'Rupal', lastName: 'Bose', gender: 'FEMALE' as const,
    email: 'rupal.bose@gmail.com', phone: '9543011005',
    dateOfBirth: new Date('1994-11-12'),
    currentLocation: 'Siliguri', city: 'Siliguri', state: 'West Bengal',
    currentDesignation: 'HR Executive', currentCompany: 'Tata Steel',
    totalExperience: 4.5, currentCTC: 700000, expectedCTC: 1000000, noticePeriod: 30,
    highestQualification: 'MBA', specialization: 'Human Resources', university: 'University of North Bengal', passingYear: 2018,
    skills: ['Recruitment', 'Onboarding', 'Payroll', 'Employee Engagement', 'Labour Laws'],
    technologyStack: ['SAP HR', 'Keka', 'MS Office'],
    status: 'NEW',
  },
  {
    firstName: 'Yash', lastName: 'Gokhale', gender: 'MALE' as const,
    email: 'yash.gokhale@gmail.com', phone: '9432011006',
    dateOfBirth: new Date('1996-01-31'),
    currentLocation: 'Kolhapur', city: 'Kolhapur', state: 'Maharashtra',
    currentDesignation: 'Mechanical Engineer – Plastic Molds', currentCompany: 'Endurance Technologies',
    totalExperience: 3.0, currentCTC: 600000, expectedCTC: 850000, noticePeriod: 30,
    highestQualification: 'B.E.', specialization: 'Mechanical Engineering', university: 'Shivaji University', passingYear: 2020,
    skills: ['Mold Design', 'Injection Molding', 'SolidWorks', 'GD&T', 'AutoCAD'],
    technologyStack: ['SolidWorks', 'AutoCAD', 'Moldflow'],
    status: 'ACTIVE',
  },
  {
    firstName: 'Shreya', lastName: 'Soni', gender: 'FEMALE' as const,
    email: 'shreya.soni@gmail.com', phone: '9321011007',
    dateOfBirth: new Date('1995-06-22'),
    currentLocation: 'Jaipur', city: 'Jaipur', state: 'Rajasthan',
    currentDesignation: 'Inside Sales Executive', currentCompany: 'Zoho Corp',
    totalExperience: 4.0, currentCTC: 650000, expectedCTC: 950000, noticePeriod: 30,
    highestQualification: 'BBA', specialization: 'Sales & Marketing', university: 'Rajasthan University', passingYear: 2018,
    skills: ['Inside Sales', 'Lead Generation', 'CRM', 'Negotiation', 'Cold Calling'],
    technologyStack: ['Zoho CRM', 'HubSpot', 'LinkedIn Sales Navigator'],
    status: 'INTERVIEWING',
  },
  {
    firstName: 'Varun', lastName: 'Mathur', gender: 'MALE' as const,
    email: 'varun.mathur@gmail.com', phone: '9210011008',
    dateOfBirth: new Date('1990-09-13'),
    currentLocation: 'Gurugram', city: 'Gurugram', state: 'Haryana',
    currentDesignation: 'Product Manager', currentCompany: 'Paytm',
    totalExperience: 10.0, currentCTC: 3000000, expectedCTC: 4200000, noticePeriod: 60,
    highestQualification: 'MBA', specialization: 'Technology Management', university: 'IIM Calcutta', passingYear: 2012,
    skills: ['Product Management', 'Agile', 'Roadmapping', 'Data Analysis', 'User Research'],
    technologyStack: ['JIRA', 'Mixpanel', 'Amplitude', 'Figma', 'SQL'],
    status: 'SHORTLISTED',
  },
  {
    firstName: 'Anjali', lastName: 'Varghese', gender: 'FEMALE' as const,
    email: 'anjali.varghese@gmail.com', phone: '9109011009',
    dateOfBirth: new Date('1993-04-05'),
    currentLocation: 'Kozhikode', city: 'Kozhikode', state: 'Kerala',
    currentDesignation: 'Logistics Coordinator', currentCompany: 'DHL Supply Chain',
    totalExperience: 6.0, currentCTC: 850000, expectedCTC: 1200000, noticePeriod: 30,
    highestQualification: 'MBA', specialization: 'Operations & Logistics', university: 'Calicut University', passingYear: 2015,
    skills: ['Logistics', 'Supply Chain', 'Customs Clearance', 'SAP WM', 'Excel'],
    technologyStack: ['SAP EWM', 'WMS', 'Cargo Wise'],
    status: 'NEW',
  },
  {
    firstName: 'Rohan', lastName: 'Joshi', gender: 'MALE' as const,
    email: 'rohan.joshi@gmail.com', phone: '9098011010',
    dateOfBirth: new Date('1997-02-20'),
    currentLocation: 'Pune', city: 'Pune', state: 'Maharashtra',
    currentDesignation: 'Trainee Software Engineer', currentCompany: 'Cognizant',
    totalExperience: 1.5, currentCTC: 450000, expectedCTC: 650000, noticePeriod: 15,
    highestQualification: 'B.Tech', specialization: 'Computer Science', university: 'MIT Pune', passingYear: 2022,
    skills: ['Java', 'SQL', 'Spring Boot', 'HTML/CSS', 'Git'],
    technologyStack: ['Java 11', 'Spring MVC', 'MySQL', 'Git'],
    status: 'NEW',
  },
];

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🌱 Seeding demo data...');

  // ── Create Clients ──────────────────────────────────────────────────────────
  console.log('  Creating 10 clients...');
  const clientMap: Record<string, string> = {};

  for (const c of CLIENTS) {
    const existing = await prisma.client.findFirst({ where: { email: c.email } });
    const client = existing ?? await prisma.client.create({ data: { ...c, isActive: true } });
    clientMap[c.companyName] = client.id;
    console.log(`    ${existing ? '↩ exists' : '✓ created'}: ${c.companyName}`);
  }

  // ── Create Jobs ─────────────────────────────────────────────────────────────
  console.log('  Creating 20 jobs...');
  const jobDefs = JOBS_BY_CLIENT(clientMap);

  for (const j of jobDefs) {
    const { requiredSkills, preferredSkills, tags, salaryMin, salaryMax, jobType, status, priority, ...rest } = j as any;
    await prisma.jobOpening.create({
      data: {
        ...rest,
        jobType: jobType as EmploymentType,
        status: status as JobStatus,
        priority: priority as JobPriority,
        requiredSkills: requiredSkills ?? null,
        preferredSkills: preferredSkills ?? null,
        tags: tags ?? null,
        salaryMin: salaryMin ?? null,
        salaryMax: salaryMax ?? null,
      },
    });
    const clientName = Object.keys(clientMap).find(k => clientMap[k] === j.clientId) ?? j.clientId;
    console.log(`    ✓ ${j.jobTitle} → ${clientName}`);
  }

  // ── Create Candidates ───────────────────────────────────────────────────────
  console.log('  Creating 50 candidates...');

  for (const c of CANDIDATES) {
    const { skills, technologyStack, status, ...rest } = c;
    const email = c.email;
    const existing = email ? await prisma.candidate.findFirst({ where: { email } }) : null;
    if (existing) {
      console.log(`    ↩ skipped (exists): ${c.firstName} ${c.lastName}`);
      continue;
    }
    await prisma.candidate.create({
      data: {
        ...rest,
        skills: skills ?? null,
        technologyStack: technologyStack ?? null,
        status: status as any,
        nationality: 'Indian',
        currentlyEmployed: true,
      },
    });
    console.log(`    ✓ ${c.firstName} ${c.lastName}`);
  }

  console.log('\n✅ Demo data seeded successfully!');
  console.log(`   Clients  : ${CLIENTS.length}`);
  console.log(`   Jobs     : ${jobDefs.length}`);
  console.log(`   Candidates: ${CANDIDATES.length}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
